version: "2.1"

services:
  main:
    image: postgres
    labels:
      svc: "live.postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456@@
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=northwind
    volumes:
      - postgresql-datavolume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgresql-datavolume: